// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/geekswamp/zen/internal/base"
	"github.com/geekswamp/zen/internal/handler/v1/user"
	"github.com/geekswamp/zen/internal/http"
	"github.com/geekswamp/zen/internal/repository"
	"github.com/geekswamp/zen/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitUserHandler() user.UserHandler {
	baseResponse := http.New()
	postgres := InitPostgres()
	db := InitGorm(postgres)
	baseRepository := base.NewRepo(db)
	userRepository := repository.NewUserRepo(baseRepository)
	userService := service.NewUserService(userRepository)
	userHandler := user.New(baseResponse, userService)
	return userHandler
}

func ProvidePostgres() *gorm.DB {
	postgres := InitPostgres()
	db := InitGorm(postgres)
	return db
}
