app:
    name: Zen
    mode: debug
    host: 127.0.0.1
    port: 8080

password:
    pepper: 2LH[l=TrkwqedS+-w7%tAnHf>VEoiA;J1emwgn9<dymPo}]DH3PmQq>zbfes!sa{
    
    argon2:
        iterations: 3
        memory: 12288
        parallelism: 1
        salt-length: 32
        key-length: 32
    
postgres:
    address: 127.0.0.1
    name:
    user:
    password: 
    port:
    sslmode: disable
    timezone: Asia/Jakarta

    base:
      conn-max-idle-time: 60
      conn-max-life-time: 60
      max-idle-conn: 60
      max-open-conn: 10

jwt:
    pub-key-path:
    priv-key-path: